### ISSUE TITLE
Only shows character-per-character definition

### ISSUE THREAD

**Issue by nicolas-raoul** [Kalamandea/Rikaichan#2]
When hovering the mouse over 日本 the add-on should show the definition of 日本 not the definition of 日

![screenshot from 2017-11-22 15-43-51](https://user-images.githubusercontent.com/99590/33113490-06acfb1a-cf9c-11e7-98b1-68191b75c24c.png)

This happens on all websites I have tried (Nikkei, Google, Gmail).

I have the default options right after installing the addon:
![screenshot from 2017-11-23 14-45-36](https://user-images.githubusercontent.com/99590/33160157-34a33bee-d05d-11e7-994e-223a79bbb1be.png)

By the way, the last 3 reviews are about this problem:
![screenshot from 2017-11-23 14-49-06](https://user-images.githubusercontent.com/99590/33160196-906897d0-d05d-11e7-8fd8-e901ec1da152.png)

**Comment by SavannahJohnston** [comment]
There are multiple modes for Rikaichan hover and lookup. Check if you have all of them activated. If so, you can press shift to alternate between them.

**Comment by nicolas-raoul** [comment]
I have the default settings, I believe, as I haven't touched any configuration since I installed the add-on.
I had Rikaichan/Rikaikun/Perapera but I guess these used separate settings. I add my options to the issue report above, do you know which one is wrong and what value it should have instead? Thanks!

**Comment by markus07** [comment]
You need to add dictionary, default is only Kanji.
But when I download and tried to add Japanese-English dictionary got this error
Error: TypeError: summary is null

**Comment by nicolas-raoul** [comment]
Ah indeed thanks @markus07!
I get this error too, for the 3 dictionaries I tried:
![screenshot from 2017-11-24 12-18-02](https://user-images.githubusercontent.com/99590/33194214-a8203ae0-d111-11e7-9359-43e281980c07.png)
The problem might be in this function: https://github.com/Kalamandea/Rikaichan/blob/dd4c14012c1204fcff443d0ab9accaaae920d701/ext/bg/js/databaseRikai.js#L66
According to [StackOverflow](https://stackoverflow.com/a/18470043/226958):
> "TypeError: [x] is null" - [...] the most common reason a JavaScript developer will get this is that they are trying to assign an event handler to a DOM element, but the DOM element hasn't been created yet.

**Comment by michaelmmason** [comment]
I have the same issue with dictionary imports, so I've opened it as a separate issue.

I was able to import dictionaries the last time I tried, which was a week or two ago. As @markus07 says, it fixes the problem @nicolas-raoul reported and Rikaichan works more-or-less the same way it used to.

**Comment by nicolas-raoul** [comment]
When #3 is fixed, the present problem should be fixed too.
