### ISSUE TITLE
Error "TypeError: summary is null" when importing a dictionary

### ISSUE THREAD

**Issue by michaelmmason** [Kalamandea/Rikaichan#3]
All attempts to import a dictionary Zip file produce the error "Error: TypeError: summary is null". I have tried the Japanese-English dictionary and the names dictionary (several times each) but get the same error every time. The error looks like this:
![image](https://user-images.githubusercontent.com/33955209/33207000-fda2ef98-d103-11e7-8a1b-9d6fabe55bc3.png)

**Comment by asdfjkl** [comment]
I can confirm that the same happens with the German-Japanese dictionary.

**Comment by Kalamandea** [comment]
Need to import new version of dictionary file from folder
https://drive.google.com/drive/folders/0BwVl0WUbZr5QQkpEdV9YS1RYNDg
First version have bug, browser used a large amount of memory in import.

**Comment by michaelmmason** [comment]
The new dictionary files fix the problem. Thanks!

**Comment by Kalamandea** [comment]
Hi!

Need to import new version of dictionary file from folder
https://drive.google.com/drive/folders/0BwVl0WUbZr5QQkpEdV9YS1RYNDg
First version have bug, browser used a large amount of memory in import.

2017-11-27 7:31 GMT+09:00 Dominik Klein <notifications@github.com>:
